#!/bin/bash -i

# Ricardo Avila 2014
#
# A script for converting .dm3 micrographs to .mrc format from the nautilus file browser GUI.
# Place this file under home/$USER/.local/share/nautilus/scripts & access from the right-click menu.
#

filename=$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS

for filename

do 
    rootname=${filename%.dm3}
    proc2d $filename $rootname.mrc mrc8bit
done
